App_Login/urls.py
from django.urls import path
from . import views

app_name = 'App_Login'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
]



App_main/urls.py
from django.urls import path
from App_main.views import *

app_name = 'App_main'

urlpatterns = [
    path('', index, name='index'),
    path('case-register/', caseRegister, name='case-register'),
    path('check-driving-license/', checkValidDrivingLicense, name='check-driving-license'),
    path('traffic-sign-book/', trafficSignBook, name='traffic-sign-book'),
    path('traffic-rules-showcase/', trafficRulesShowcase, name='traffic-rules-showcase'),
]

traffic_control_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('App_Login.urls')),
    path('driver/', include('App_driver.urls')),
    path('traffic/', include('App_traffic.urls')),
    path('', include('App_main.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Login/models.py
from django.db import models

# Create your models here.

App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

App_Login/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.contrib.auth.forms import  UserCreationForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout
from App_Login.forms import SignupForm


# Create your views here.
def is_traffic_(user):
    return user.groups.filter(name='Traffic').exists()


def is_driver_(user):
    return user.groups.filter(name='Driver').exists()


def register_view(request):
    form = SignupForm()
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            grp = Group.objects.get_or_create(name='Driver')
            grp[0].user_set.add(user)
            return HttpResponseRedirect(reverse('App_Login:login'))
    content = {
        'form': form
    }
    return render(request, 'App_Login/register.html', context=content)


def login_view(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('App_main:index'))
        else:
            return render(request, 'App_Login/login.html', {'error': 'username or password is incorrect.'})
    return render(request, 'App_Login/login.html')


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('App_Login:login'))


templates/App_Login/login.html
{% load static %}
{% load crispy_forms_filters %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="favicon" href="{% static 'images/icons/traffic-light.png' %}" type="image/png" sizes="192x192" />
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" 
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" 
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/loginPage.css' %}">
    <!-- Text Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Marcellus&display=swap" rel="stylesheet">
    <title>Login System</title>
    {% include "App_Login/loginCSS.html" %}
    <style>
        body {
            background: url("{% static 'images/background_of_login_page(1).jpg' %}") no-repeat;
            background-size: cover;
            opacity: 0.8;
            color: #ffffff !important;
        }

        .heading-1 {
            text-align: center;
            color: #000000;
        }

        .form-container{
            background: #000000;
            color: #ffffff;
        }

        .form-container label {
            color: #ffffff;
        }

        .form-container input {
            font-weight: bold;
        }
    </style>
  </head>
  <body>
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 margin_top_15 padding-bottom-5-prcnt form-content">
        <div class="fr_lr con-img">
        <div class="container-fluid ">
            <div class="col-md-12">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center clearfix" style="height: auto;padding: 20px 0px">
                        <h1 class="heading-1 google_marcellus_SC">
                            <span> Traffic Management </span>
                        </h1>
                    </div>
        <div class="col-sm-12 col-sm-12 col-xs-12 mb-5" style="margin-top: 80px; margin-bottom: 100px;">
            <div class="row ">
                <div class="col-md-3">
                </div>
                <div class="col-md-6 form-container">
                    <form method="post">
                        {% csrf_token %}
                        <legend class="text-center">
                            <h2 class="heading-2 google_marcellus_SC">
                                <span>Login</span>
                            </h2>
                        </legend>
                            <div class="form-group input-container">
                                <label for="username" class="google_marcellus_SC">Username</label>
                                <input type="text" class="form-control" id="username" name="username" placeholder="Enter username" required>
                            </div>
                            <div class="form-group input-container">
                                <label for="password" class="google_marcellus_SC">Password</label>
                                <input type="password" class="form-control" id="password" name="password" placeholder="Enter password" required>
                                <div style="float: right; margin-right: 10px; margin-top: -30px;">
                                    <i class="bi bi-eye-fill" id="showPassword" onclick="showPassword()"></i>
                                </div>
                            </div>
                            <div class="form-group mt-3 text-center">
                                <button type="submit" class="loginBtn google_marcellus_SC">Login</button>
                            </div>
                        </form>
                        <div class="text-center form-group mt-4">
                            <a href="#" class="forgot-password google_marcellus_SC">Forgot Password?</a>
                        </div>
                    </form>
                </div>
                <div class="col-md-3">
                </div>
            </div>
        </div>
            <!--== Show Left widget when screen is sm and xs-->
                        <!--- -->
            </div>
        </div>
        <div class="container">
            <div class="text-center text-dark">
                <p>
                    I don't have an account? 
                    <a href="{% url 'App_Login:register' %}" class="google_marcellus_SC">
                        <span onclick="alert('You can only register as a driver. When You have a valid driving license.')">
                            Register Now
                        </span>
                    </a>
                </p>
            </div>
            <div class="text-center text-dark">
                <p class="google_marcellus_SC">
                    <span>Copyright &copy; 2022</span>
                </p>
            </div>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <script>
        const showPassword = () => {
            const password = document.getElementById('password');
            const eye = document.querySelector('#showPassword');
            if (password.type === 'password') {
                password.type = 'text';
                eye.classList.remove('bi-eye-fill');
                eye.classList.add('bi-eye-slash-fill');
            } else {
                password.type = 'password';
                eye.classList.remove('bi-eye-slash-fill');
                eye.classList.add('bi-eye-fill');
            }
        }
    </script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
     integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" 
     crossorigin="anonymous"></script>
  </body>
</html>

templates/App_Login/loginCSS.html
<style>
    .loginBtn {
        font-family: 'Marcellus', serif !important;
        color: white !important;
        background-color: #0073bb !important;
        border: 1px solid #0073bb !important;
        border-radius: 5px !important;
        padding: 5px !important;
        width: 60%;
    }

    .loginBtn:hover {
        background-color: #0073bb !important;
        border: 1px solid #0073bb !important;
        color: white !important;
    }

    .form-container {
        padding: 20px;
        border: 1px solid #131b43 !important;
        border-radius: 5px !important;
    }

    .input-container {
        width: 100%;
        margin-top: 20px;
    }

    .form-group {
        margin-top: 20px;
    }

    .forgot-password {
        color: yellow !important;
        text-decoration: none;
    }

    #showPassword {
        color: red !important;
    }
</style>

templates/App_Login/register.html
{% load static %}
{% load crispy_forms_filters %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="favicon" href="{% static 'images/icons/traffic-light.png' %}" type="image/png" sizes="192x192" />
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" 
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" 
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/loginPage.css' %}">
    <!-- Text Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Marcellus&display=swap" rel="stylesheet">
    <title>Login System</title>
    {% include "App_Login/loginCSS.html" %}
    <style>
        body {
            background: url("{% static 'images/background_of_login_page.jpg' %}");
            background-repeat: no-repeat;
            background-size: cover;
            opacity: 0.8;
            color: #ffffff !important;
        }

        .heading-1 {
            text-align: center;
            color: #000000;
            font-size: 24px;
        }

        .form-container{
            background: #000000;
            color: #ffffff;
        }

        .form-container label {
            color: #ffffff;
        }

        .form-container input {
            font-weight: bold;
        }
    </style>
  </head>
  <body>
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 margin_top_15 padding-bottom-5-prcnt">
        <div class="fr_lr con-img">
        <div class="container-fluid ">
            <div class="col-md-12">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center clearfix" style="height: auto;padding: 20px 0px">
                        <h1 class="heading-1 google_marcellus_SC">
                            <span> Digital Traffic Case Handling Protal</span>
                        </h1>
                    </div>
        <div class="col-sm-12 col-sm-12 col-xs-12 mb-5" style="margin-top: 40px; margin-bottom: 100px;">
            <div class="row ">
                <div class="col-md-3">
                </div>
                <div class="col-md-6 form-container">
                    <form method="post">
                        {% csrf_token %}
                        <legend class="text-center">
                            <h2 class="heading-2 google_marcellus_SC" style="margin-bottom: 0;">
                                <span>
                                    Sign up
                                </span>
                            </h2>
                            <small style="font-size: 13px;">(You must have a driving licence)</small>
                        </legend>
                        {{ form|crispy }}
                        <div>
                            <label for="id-passwordShow" style="curson: pointer;">
                                <input type="checkbox" class="checkbox" id="id-passwordShow" onclick="showPassword()" >
                                <span class="checkbox-custom" id="passwordShowLabel"> Show Password </span>
                            </label>
                        </div>
                        <div class="form-group mt-3 text-center">
                            <button type="submit" class="loginBtn google_marcellus_SC">Signup</button>
                        </div>
                    </form>
                </div>
                <div class="col-md-3">
                </div>
            </div>
        </div>
            <!--== Show Left widget when screen is sm and xs-->
            <!--- -->
            </div>
        </div>
        <div class="container">
            <div class="text-center">
                <p>
                    I have registered. <a href="{% url 'App_Login:login' %}">Sign In</a>
                </p>
            </div>
            <div class="text-center">
                <p class="google_marcellus_SC">
                    <span>Copyright &copy; 2022</span>
                </p>
            </div>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <script>
        const showPassword = () => {
            const password1 = document.getElementById('id_password1');
            const password2 = document.getElementById('id_password2');
            const passwordShowLabel = document.getElementById('passwordShowLabel');
            if (password1.type === 'password' && password2.type === 'password') {
                password1.type = 'text';
                password2.type = 'text';
                passwordShowLabel.innerHTML = 'Hide Password';
            } else {
                password1.type = 'password';
                password2.type = 'password';
                passwordShowLabel.innerHTML = 'Show Password';
            }
        }
    </script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
     integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" 
     crossorigin="anonymous"></script>
  </body>
</html>