App_Login/urls.py
from django.urls import path
from . import views

app_name = 'App_Login'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
]



App_driver/urls.py
from django.urls import path
from . import views

app_name = 'App_driver'

urlpatterns = [
    path('profile-setup/', views.profile_setup, name='profile-setup'),
    path('new-cases/', views.newCases, name='new-cases'),
    path('license-and-validation/', views.license_and_validation, name='license-and-validation'),
    path('traffic-rules/', views.traffic_rules, name='traffic-rules'),
    path('license-renew/', views.license_renew, name='license-renew'),
]


App_main/urls.py
from django.urls import path
from App_main.views import *

app_name = 'App_main'

urlpatterns = [
    path('', index, name='index'),
    path('case-register/', caseRegister, name='case-register'),
    path('check-driving-license/', checkValidDrivingLicense, name='check-driving-license'),
    path('traffic-sign-book/', trafficSignBook, name='traffic-sign-book'),
    path('traffic-rules-showcase/', trafficRulesShowcase, name='traffic-rules-showcase'),
]

traffic_control_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('App_Login.urls')),
    path('driver/', include('App_driver.urls')),
    path('traffic/', include('App_traffic.urls')),
    path('', include('App_main.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_driver/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import *
from django.utils.translation import gettext_lazy as _

# Create your models here.
bangladeshi_mobile_number_regex = RegexValidator(regex=r"^\+?(88)01[3-9][0-9]{8}$",
                                                 message=_('Enter Bangladeshi Number with country code'))


class DriverModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='drivers')
    driving_license = models.CharField(max_length=100)
    license_last_validation_date = models.DateField(blank=True, null=True)
    mobile_number = models.CharField(max_length=16, validators=[bangladeshi_mobile_number_regex])
    house = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    division = models.CharField(max_length=100)
    zipcode = models.PositiveBigIntegerField()
    validate = models.BooleanField(default=False)
    Profile_photo = models.ImageField(upload_to='Drivers/profile_picture', default=None, null=True)
    created_date = models.DateField(auto_created=True)

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}'s-{self.driving_license}"


class TransactionModel(models.Model):
    user = models.ForeignKey(DriverModel, on_delete=models.DO_NOTHING, related_name='transaction_driver')
    name = models.CharField(max_length=100)
    sending_number = models.CharField(max_length=100)
    upload_screenshot = models.ImageField(upload_to='upload_screenshot')
    transaction_id = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.name} sends driving license money with {self.sending_number}, transaction ID: {self.transaction_id}"

App_driver/forms.py
from django import forms
from App_driver.models import DriverModel


class DriverModelForm(forms.ModelForm):
    class Meta:
        model = DriverModel
        exclude = ['user', ]



App_driver/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from App_driver.forms import *
from App_main.models import *
from App_Login.models import *
from App_traffic.models import *


# Create your views here.
def profile_setup(request):
    profileForm = DriverModelForm()
    if request.method == 'POST':
        profileForm = DriverModelForm(request.POST)
        if profileForm.is_valid():
            thisProfile = profileForm.save(commit=False)
            thisProfile.user = request.user
            thisProfile.save()
            return redirect('App_main:index')
        else:
            return render(request, "profile_setup.html")
    content = {
        'form': profileForm,
    }
    return render(request, "App_driver/profile_setup.html", context=content)


def newCases(request):
    driver = DriverModel.objects.get(user=request.user)
    all_case = CaseModel.objects.filter(accused=driver)
    content = {
        'all_case': all_case
    }
    return render(request, 'App_driver/all_cases.html', context=content)


def license_and_validation(request):
    driver = DriverModel.objects.get(user=request.user)
    content = {
        'driver': driver
    }
    return render(request, 'App_driver/my_license.html', context=content)


def traffic_rules(request):
    all_offences = PenaltyModel.objects.all()
    content = {
        'all_offences': all_offences
    }
    return render(request, 'App_driver/traffic_rules.html', context=content)


def license_renew(request):
    driver = DriverModel.objects.get(user=request.user)
    if request.method == 'POST':
        name = request.POST.get('name')
        sendingNumber = request.POST.get('sending_number')
        uploadedScreenShot = request.FILES.get('screenshot')
        transactionID = request.POST.get('transactionID')
        upload = TransactionModel(name=name, sending_number=sendingNumber, upload_screenshot=uploadedScreenShot,
                                  transaction_id=transactionID)
        upload.user = driver
        upload.save()
        return HttpResponseRedirect(reverse('App_driver:license-renew'))
    return render(request, 'App_driver/license_renew.html')

templates/App_driver/all_cases.html
{% extends 'App_driver/basement.html' %}
{% block title %}
    Cases
{% endblock %}
{% block main %}
    <style>
        .young-passion-gradient {
            background-image: -webkit-gradient(linear, left top, right top, from(#ff8177), color-stop(0, #ff867a), color-stop(21%, #ff8c7f), color-stop(52%, #f99185), color-stop(78%, #cf556c), to(#b12a5b));
            background-image: linear-gradient(to right, #ff8177 0, #ff867a 0, #ff8c7f 21%, #f99185 52%, #cf556c 78%, #b12a5b 100%);
        }

        .tempting-azure-gradient {
            background-image: linear-gradient(120deg, #84fab0 0, #8fd3f4 100%);
        }

        .purple-gradient {
            background: linear-gradient(40deg, #ff6ec4, #7873f5) !important;
        }

        small {
            font-size: 11px !important;
        }
    </style>
    <div class="container mt-4">
        <div class="container">
            <div class="row">
                {% for case in all_case %}
                    <div class="col-md-4">
                        <div class="young-passion-gradient card" style="width: 18rem;">
                            <div class="card-body">
                                <h5 class="card-title">
                                    {{ case.offence.description }}, ধারাঃ {{ case.offence.in_section }}
                                </h5>
                                <p class="card-text text-right text-white"
                                   style="font-size: 18px !important;">
                                    <span>জরিমানাঃ {{ case.cost_of_penalty }}/-</span> <br>
                                    <small class="text-right">
                                        {{ case.registered_time }}
                                    </small>
                                </p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}
{% block newCases %}
dashboard.classList.remove('active');
newCases.classList.add('active');
myLicense.classList.remove('active');
licenseRenew.classList.remove('active');
trafficRules.classList.remove('active');
{% endblock newCases %}


templates/App_driver/base.html
{% load static %}
<!DOCTYPE html>
<!-- Created by Traffic Management System -->
<html lang="en" dir="ltr">

<head>
  <meta charset="UTF-8">
  <!-- Boxiocns CDN Link -->
  <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" 
  rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Marcellus&family=Marcellus+SC&display=swap" rel="stylesheet">
  <title>Digital Traffic Case Handling Protal | 
    {% block title %}
    {% endblock  %}
  </title>
  <style>
    /* Google Fonts Import Link */
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap');
    *{
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        {% comment %} font-family: 'Poppins', sans-serif; {% endcomment %}
        font-family: 'Marcellus', serif !important;
    }
    .wrapper{
        display: flex;
        min-height: 100%;
    }
    .sidebar{
        display: flex;
        flex-direction: column;
        margin-bottom: 0;
        min-height: 100vh;
        width: 260px;
        background-image: -webkit-gradient(linear,left bottom,left top,from(#a8edea),to(#fed6e3));
        background-image: linear-gradient(to top,#a8edea 0,#fed6e3 100%);
        background-size: cover;
        z-index: 100;
        transition: all 0.5s ease;
    }
    .sidebar.close{
        width: 78px;
    }
    .sidebar .logo-details{
        height: 60px;
        width: 100%;
        display: flex;
        align-items: center;
    }
    .sidebar .logo-details i{
        font-size: 30px;
        color: #fff;
        height: 50px;
        min-width: 78px;
        text-align: center;
        line-height: 50px;
    }
    .sidebar .logo-details .logo_name{
        font-size: 22px;
        color: #000;
        font-weight: 600;
        transition: 0.3s ease;
        transition-delay: 0.1s;
    }
    .sidebar.close .logo-details .logo_name{
        transition-delay: 0s;
        opacity: 0;
        pointer-events: none;
    }
    .sidebar .nav-links{
        height: 100%;
        padding: 30px 0 100px 0;
        overflow: auto;
    }
    .sidebar.close .nav-links{
        overflow: visible;
    }
    .sidebar .nav-links::-webkit-scrollbar{
        display: none;
    }
    .sidebar .nav-links li{
        position: relative;
        list-style: none;
        transition: all 0.4s ease;
    }
    .sidebar .nav-links li:hover{
        background: #1d1b31;
    }
    .sidebar .nav-links li .icon-link{
        display: flex;
        align-items: center;
        justify-content: space-between;
    }
    .sidebar.close .nav-links li .icon-link{
        display: block
    }
    .sidebar .nav-links li i{
        height: 50px;
        min-width: 78px;
        text-align: center;
        line-height: 50px;
        color: red;
        font-size: 20px;
        cursor: pointer;
        transition: all 0.3s ease;
    }
    .sidebar .nav-links li.showMenu i.arrow{
        transform: rotate(-180deg);
    }
    .sidebar.close .nav-links i.arrow{
        display: none;
    }
    .sidebar .nav-links li a{
        display: flex;
        align-items: center;
        text-decoration: none;
    }
    .sidebar .nav-links li a .link_name{
        font-size: 18px;
        font-weight: 400;
        color: #000;
        transition: all 0.4s ease;
        font-family: 'Marcellus', serif !important;
    }

    .sidebar .nav-links li a .link_name:hover {
        font-size: 18px;
        font-weight: 400;
        color: #fff;
        transition: all 0.4s ease;
        font-family: 'Marcellus', serif !important;
    }

    .sidebar.close .nav-links li a .link_name{
        opacity: 0;
        pointer-events: none;
        font-weight: 400;
        font-family: 'Marcellus', serif !important;
    }
    .sidebar .nav-links li .sub-menu{
        padding: 6px 6px 14px 80px;
        margin-top: -10px;
        background: #1d1b31;
        display: none;
    }
    .sidebar .nav-links li.showMenu .sub-menu{
        display: block;
    }
    .sidebar .nav-links li .sub-menu a{
        color: #fff;
        font-size: 15px;
        padding: 5px 0;
        white-space: nowrap;
        opacity: 0.6;
        transition: all 0.3s ease;
    }
    .sidebar .nav-links li .sub-menu a:hover{
        opacity: 1;
    }
    .sidebar.close .nav-links li .sub-menu{
        position: absolute;
        left: 100%;
        top: -10px;
        margin-top: 0;
        padding: 10px 20px;
        border-radius: 0 6px 6px 0;
        opacity: 0;
        display: block;
        pointer-events: none;
        transition: 0s;
    }
    .sidebar.close .nav-links li:hover .sub-menu{
        top: 0;
        opacity: 1;
        pointer-events: auto;
        transition: all 0.4s ease;
    }
    .sidebar .nav-links li .sub-menu .link_name{
        display: none;
    }
    .sidebar.close .nav-links li .sub-menu .link_name{
        font-size: 18px;
        opacity: 1;
        display: block;
    }
    .sidebar .nav-links li .sub-menu.blank{
        opacity: 1;
        pointer-events: auto;
        padding: 3px 20px 6px 16px;
        opacity: 0;
        pointer-events: none;
    }
    .sidebar .nav-links li:hover .sub-menu.blank{
        top: 50%;
        transform: translateY(-50%);
    }
    .sidebar .profile-details{
        position: fixed;
        bottom: 0;
        width: 260px;
        display: flex;
        align-items: center;
        justify-content: space-between;
        background: #1d1b31;
        padding: 12px 0;
        transition: all 0.5s ease;
    }
    .sidebar.close .profile-details{
        background: none;
    }
    .sidebar.close .profile-details{
        width: 78px;
    }
    .sidebar .profile-details .profile-content{
        display: flex;
        align-items: center;
    }
    .sidebar .profile-details img{
        height: 52px;
        width: 52px;
        object-fit: cover;
        border-radius: 16px;
        margin: 0 14px 0 12px;
        background: #1d1b31;
        transition: all 0.5s ease;
    }
    .sidebar.close .profile-details img{
        padding: 10px;
    }
    .sidebar .profile-details .profile_name,
    .sidebar .profile-details .job{
        color: #fff;
        font-size: 18px;
        font-weight: 500;
        white-space: nowrap;
    }
    .sidebar.close .profile-details i,
    .sidebar.close .profile-details .profile_name,
    .sidebar.close .profile-details .job{
        display: none;
    }
    .sidebar .profile-details .job{
        font-size: 12px;
    }
    .home-section{
        position: relative;
        background: #E4E9F7;
        min-height: 100%;
        left: 0px;
        width: calc(100% - 260px);
        transition: all 0.5s ease;
    }
    .sidebar.close ~ .home-section{
        left: 0px;
        width: calc(100% - 78px);
    }
    .home-section .home-content{
        height: 60px;
        display: flex;
        align-items: center;
    }
    .home-section .home-content .bx-menu,
    .home-section .home-content .text{
        color: #11101d;
        font-size: 35px;
    }
    .home-section .home-content .bx-menu{
        margin: 0 15px;
        cursor: pointer;
    }
    .home-section .home-content .text{
        font-size: 26px;
        font-weight: 500;
    }
    @media (max-width: 400px) {
        .sidebar.close.small-screen{
            width: 0;
        }

        .sidebar.close.small-screen ~ .home-section{
            width: 100%;
            left: 0;
            z-index: 100;
        }
    }

  </style>
</head>
<body>
  <div class="wrapper">
    <div class="sidebar">
      <div class="logo-details">
        <img src="{% static 'images/icons/driver.png' %}" 
        alt="Traffic Police Icon" style="width: 50px; height: 50px; padding: 5px;">
        <span class="logo_name">General Driver</span>
      </div>
      <ul class="nav-links">
        <li>
          <a href="#">
            <i class='bx bx-grid-alt'></i>
            <span class="link_name">Dashboard</span>
          </a>
          <ul class="sub-menu blank">
            <li><a class="link_name" href="#">Dashboard</a></li>
          </ul>
        </li>
        <li>
          <a href="#">
            <i class='bx bx-grid-alt'></i>
            <span class="link_name">Dashboard</span>
          </a>
          <ul class="sub-menu blank">
            <li><a class="link_name" href="#">Dashboard</a></li>
          </ul>
        </li>
        <li>
          <div class="icon-link">
            <a href="#">
              <i class='bx bx-collection'></i>
              <span class="link_name">Category</span>
            </a>
            <i class='bx bxs-chevron-down arrow'></i>
          </div>
          <ul class="sub-menu">
            <li><a class="link_name" href="#">Category</a></li>
            <li><a href="#">HTML & CSS</a></li>
            <li><a href="#">JavaScript</a></li>
            <li><a href="#">PHP & MySQL</a></li>
          </ul>
        </li>
        <li>
          <div class="profile-details">
            <div class="profile-content">
              
            </div>
            <div class="name-job">
              <div class="profile_name">{{ request.user.username }}</div>
              <div class="job">{{ profile.driving_license }}</div>
            </div>
            <i class='bx bx-log-out' onclick="window.location.href='{% url "App_Login:logout" %}'"></i>
          </div>
        </li>
      </ul>
    </div>
    <section class="home-section">
      <div class="home-content">
        <i class='bx bx-menu'></i>
        <span class="text"> Digital Traffic Case Handling Protal </span> <br />
    </div>
    <div>
        {% block main %}
        {% endblock %}
    </div>

    </section>
  </div>

  <script>
    let arrow = document.querySelectorAll(".arrow");
    for (var i = 0; i < arrow.length; i++) {
      arrow[i].addEventListener("click", (e) => {
        let arrowParent = e.target.parentElement.parentElement;//selecting main parent of arrow
        arrowParent.classList.toggle("showMenu");
      });
    }
    let sidebar = document.querySelector(".sidebar");
    let sidebarBtn = document.querySelector(".bx-menu");
    console.log(sidebarBtn);
    /* sidebarBtn.addEventListener("click", () => {
      sidebar.classList.toggle("close");
    }); */
    $(function () {
      /* console.log("width: "+ document.body.clientWidth); */
      
      resizeScreen();
      $(window).resize(function(){
        resizeScreen();
      });
      $('.bx-menu').click(function(){

        if(document.body.clientWidth > 400){
          $('.sidebar').toggleClass('close');
        }else{
          $('.sidebar').toggleClass('small-screen');
        }
      });
      
      function resizeScreen() {
        if(document.body.clientWidth < 400){
          $('.sidebar').addClass('close');
        }else{
          $('.sidebar').removeClass('close');
        }
      }
    });
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" 
  integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>

</html>

templates/App_driver/dashboard.html
{% extends 'App_driver/basement.html' %}
{% block title %}
    Driver Dashboard
{% endblock %}
{% block main %}
    <style>  
        .young-passion-gradient {
            background-image: -webkit-gradient(linear,left top,right top,from(#ff8177),color-stop(0,#ff867a),color-stop(21%,#ff8c7f),color-stop(52%,#f99185),color-stop(78%,#cf556c),to(#b12a5b));
            background-image: linear-gradient(to right,#ff8177 0,#ff867a 0,#ff8c7f 21%,#f99185 52%,#cf556c 78%,#b12a5b 100%);
        }

        .tempting-azure-gradient {
            background-image: linear-gradient(120deg,#84fab0 0,#8fd3f4 100%);
        }

        .purple-gradient {
            background: linear-gradient(40deg,#ff6ec4,#7873f5) !important;
        }
    </style>
    <div class="container mt-4">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="young-passion-gradient card" style="width: 18rem;">
                        <div class="card-body">
                            <h5 class="card-title">
                                Case Notification
                            </h5>
                            <p class="card-text float-end text-white" style="font-size: 28px !important;">
                                2
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="tempting-azure-gradient card" style="width: 18rem;">
                        <div class="card-body">
                            <h5 class="card-title">
                                Warning
                            </h5>
                            <p class="card-text float-end text-dark" style="font-size: 28px !important;">
                                2
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="purple-gradient card" style="width: 18rem;">
                        <div class="card-body">
                            <h5 class="card-title">
                                Reserved Point
                            </h5>
                            <p class="card-text float-end text-white" style="font-size: 28px !important;">
                                2
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
dashboard.classList.add('active');
newCases.classList.remove('active');
myLicense.classList.remove('active');
licenseRenew.classList.remove('active');
trafficRules.classList.remove('active');
{% endblock script %}

templates/App_driver/license_renew.html
{% extends 'App_driver/basement.html' %}
{% load static %}
{% block title %}
    License Renew
{% endblock %}
{% block main %}
    <style>
        .card-body img {
            width: 100%;
            height: 100%;
        }

        .card-body p {
            margin-top: 20px;
            text-align: center;
        }
    </style>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <div class="container" id="id-scanning-qr">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <div class="justify-content-center mt-lg-5">
                    <div class="card card-tale">
                        <div class="card-body">
                            <img src="{% static 'images/qrcode.png' %}" alt="Payment QR code">
                            <p class="fs-30 mb-2">Pay with BKash</p>
                            <p>Scan It and Pay (Reference: License Number)</p>
                            <p>
                                <button class="btn btn-primary" onclick="submitPaymentInfo(0)">Done</button>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>
    <div class="container" id="id-payment-information" style="display: none;">
        <div class="col-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title text-center">Submit Payment Info</h4>
                    <form class="forms-sample" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="exampleInputName1">Name</label>
                            <input name="name" type="text" class="form-control" id="exampleInputName1" placeholder="Name">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword4">Sending Number</label>
                            <input type="text" class="form-control" id="exampleInputPassword4" name="sending_number"
                                   placeholder="Sending Number">
                        </div>
                        <div class="form-group">
                            <label>Upload Screenshot</label>
                            <input type="file" name="screenshot" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword4">Transaction ID</label>
                            <input type="text" class="form-control" id="exampleInputPassword4" name="transactionID"
                                   placeholder="Transaction ID">
                        </div>
                        <button type="submit" class="btn btn-primary mr-2">Submit</button>
                        <button class="btn btn-light" onclick="submitPaymentInfo(1)">Cancel</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script>
        const licenseValidationTest = (expectedValue) => {
            if (expectedValue === 0) {
                Swal.fire({
                    icon: 'error',
                    title: 'Oops...',
                    text: 'Your license timeout!',
                    footer: '<a href="{% url 'App_main:case-register' %}">রিনিউ করতে চান?</a>'
                })
            } else {
                Swal.fire(
                    'Good Job!',
                    'Your license is validated!',
                    'success'
                )
            }
        }

        const submitPaymentInfo = (v) => {
            if (v === 0) {
                document.getElementById('id-payment-information').style.display = 'block';
                document.getElementById('id-scanning-qr').style.display = 'none';
            } else if (v === 1) {
                document.getElementById('id-payment-information').style.display = 'none';
                document.getElementById('id-scanning-qr').style.display = 'block';
            }
        }
    </script>
{% endblock %}
{% block script %}
dashboard.classList.remove('active');
newCases.classList.remove('active');
myLicense.classList.remove('active');
licenseRenew.classList.add('active');
trafficRules.classList.remove('active');
{% endblock script %}


templates/App_driver/profile_setup.html
{% load static %}
{% load crispy_forms_filters %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="favicon" href="{% static 'images/icons/traffic-light.png' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/loginPage.css' %}">
    <!-- Text Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Marcellus&display=swap" rel="stylesheet">
    <title>Profile Setup</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    {% include "App_Login/loginCSS.html" %}
</head>
<body>
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 margin_top_15 padding-bottom-5-prcnt">
        <div class="fr_lr con-img">
        <div class="container-fluid ">
            <div class="col-md-12">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center clearfix" style="height: auto;padding: 20px 0px">
                        <h1 class="heading-1 google_marcellus_SC">
                            <span> Traffic Management</span>
                        </h1>
                    </div>
        <div class="col-sm-12 col-sm-12 col-xs-12 mb-5" style="margin-top: 40px; margin-bottom: 100px;">
            <div class="row ">
                <div class="col-md-3">
                </div>
                <div class="col-md-6 form-container">
                    <form method="post">
                        {% csrf_token %}
                        <legend class="text-center">
                            <h2 class="heading-2 google_marcellus_SC" style="margin-bottom: 0;">
                                <span>
                                    Profile Setup
                                </span>
                            </h2>
                        </legend>
                        {{ form|crispy }}
                        <div class="form-group mt-3 text-center">
                            <button type="submit" class="loginBtn google_marcellus_SC">Signup</button>
                        </div>
                    </form>
                </div>
                <div class="col-md-3">
                </div>
            </div>
        </div>
            <!--== Show Left widget when screen is sm and xs-->
                        <!--- -->
            </div>
        </div>
        <div class="container">
            <div class="text-center">
                <p>
                    I have registered. <a href="{% url 'App_Login:login' %}">Sign In</a>
                </p>
            </div>
            <div class="text-center">
                <p class="google_marcellus_SC">
                    <span>Copyright &copy; 2022</span>
                </p>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>