App_Login/urls.py
from django.urls import path
from . import views

app_name = 'App_Login'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
]



App_main/urls.py
from django.urls import path
from App_main.views import *

app_name = 'App_main'

urlpatterns = [
    path('', index, name='index'),
    path('case-register/', caseRegister, name='case-register'),
    path('check-driving-license/', checkValidDrivingLicense, name='check-driving-license'),
    path('traffic-sign-book/', trafficSignBook, name='traffic-sign-book'),
    path('traffic-rules-showcase/', trafficRulesShowcase, name='traffic-rules-showcase'),
]

traffic_control_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('App_Login.urls')),
    path('driver/', include('App_driver.urls')),
    path('traffic/', include('App_traffic.urls')),
    path('', include('App_main.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_main/models.py
from django.db import models
from App_driver.models import *
from App_traffic.models import *


# Create your models here.
class PenaltyModel(models.Model):
    in_section = models.CharField(max_length=50)
    description = models.TextField()
    penalty_imposed_on_1st_time = models.CharField(max_length=250)
    penalty_imposed_on_2nd_time = models.CharField(max_length=250, blank=True)

    def __str__(self):
        return f"{self.in_section}-{self.description}-(প্রথমবার ধার্যকৃতঃ{self.penalty_imposed_on_1st_time})-(২য়বার ধার্যকৃতঃ {self.penalty_imposed_on_2nd_time})"


class CaseModel(models.Model):
    registered_by = models.ForeignKey(TrafficOfficerModel, on_delete=models.CASCADE, related_name='case_registered_by')
    accused = models.ForeignKey(DriverModel, on_delete=models.CASCADE, related_name='case_on_driver')
    vehicle_number = models.CharField(max_length=50, blank=False)
    offence = models.ForeignKey(PenaltyModel, on_delete=models.CASCADE, related_name='offence_of_driver')
    offence_happens_in_place = models.CharField(max_length=200)
    cost_of_penalty = models.IntegerField(default=0)
    caseType = models.CharField(max_length=50, blank=True)
    occurrence_happened_time = models.DateTimeField()
    registered_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"A Case registerd on {self.registered_time} for {self.accused}"

App_main/forms.py
from django import forms
from App_main.models import CaseModel


class CaseModelForm(forms.ModelForm):
    occurrence_happened_time = forms.CharField(widget=forms.TextInput(attrs={'type': 'datetime-local'}))

    class Meta:
        model = CaseModel
        exclude = ['accused', 'registered_by', ]

App_main/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse
from django.contrib.auth.decorators import login_required
from App_driver.models import *
from App_main.forms import *
from App_main.models import *
from App_Login.models import *
from App_traffic.models import *
from App_Login.views import is_traffic_, is_driver_
import datetime


# Create your views here.
@login_required
def index(request):
    if is_traffic_(request.user):
        profile = TrafficOfficerModel.objects.filter(user=request.user)
        if profile.exists():
            traffic = profile[0]
            all_reports = CaseModel.objects.filter(registered_by=traffic)
            total_credits = all_reports.count() * 50
            content = {
                'traffic': traffic,
                'all_reports': all_reports,
            }
            return render(request, 'App_traffic/index.html', context=content)
        else:
            return HttpResponseRedirect(reverse('App_Login:login'))
    else:
        profile = DriverModel.objects.filter(user=request.user)
        driver = profile[0]
        if driver.license_last_validation_date < datetime.date.today():
            driver.validate = False
            driver.save()
        if profile.exists():
            content = {
                'profile': profile[0]
            }
            return render(request, 'App_driver/dashboard.html', context=content)
        else:
            return HttpResponseRedirect(reverse('App_driver:profile-setup'))


def caseRegister(request):
    all_penalty = PenaltyModel.objects.all()
    all_driver = DriverModel.objects.all()
    traffic_police = TrafficOfficerModel.objects.get(user=request.user)
    form = CaseModelForm()
    if request.method == 'POST':
        accused_info = request.POST.get('accused')
        accused = all_driver.get(id=accused_info)
        form = CaseModelForm(request.POST)
        if form.is_valid():
            thisForm = form.save(commit=False)
            thisForm.registered_by = traffic_police
            thisForm.accused = accused
            thisForm.save()
            return HttpResponseRedirect(reverse('App_main:case-register'))
    content = {
        'form': form,
        'all_penalty': all_penalty,
        'all_driver': all_driver,
    }
    return render(request, 'App_main/case_register.html', context=content)


def checkValidDrivingLicense(request):
    all_driver = DriverModel.objects.all()
    content = {
        'all_driver': all_driver
    }
    return render(request, 'App_main/checkDrivingLicense.html', context=content)


def trafficSignBook(request):
    return render(request, 'App_main/rule_book.html')


def trafficRulesShowcase(request):
    all_offences = PenaltyModel.objects.all()
    content = {
        'all_offences': all_offences
    }
    return render(request, 'App_main/traffic_rule.html', context=content)

templates/App_main/base.html
{% load static %}
<!DOCTYPE html>
<!-- Created by Traffic Management System -->
<html lang="en" dir="ltr">

<head>
  <meta charset="UTF-8">
  <!-- Boxiocns CDN Link -->
  <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/App_traffic/base.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" 
  rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Marcellus&family=Marcellus+SC&display=swap" rel="stylesheet">
  <title>Digital Traffic Case Handling Protal | 
    {% block title %}
    {% endblock  %}
  </title>
</head>
<body>
  <div class="wrapper">
    <div class="sidebar">
      <div class="logo-details">
        <img src="{% static 'images/icons/Traffic_police.png' %}" 
        alt="Traffic Police Icon" style="width: 50px; height: 50px; padding: 5px;">
        <span class="logo_name">Taffic Officer</span>
      </div>
      <ul class="nav-links">
        <li>
          <a href="#">
            <i class='bx bx-grid-alt'></i>
            <span class="link_name">Dashboard</span>
          </a>
          <ul class="sub-menu blank">
            <li><a class="link_name" href="#">Dashboard</a></li>
          </ul>
        </li>
        <li>
          <a href="{% url 'App_main:case-register' %}">
            <i class='bx bx-grid-alt'></i>
            <span class="link_name">Case Register</span>
          </a>
          <ul class="sub-menu blank">
            <li>
                <a class="link_name" href="#">
                    Case Register
                </a>
            </li>
          </ul>
        </li>
        <li>
          <div class="icon-link">
            <a href="#">
              <i class='bx bx-collection'></i>
              <span class="link_name">Category</span>
            </a>
            <i class='bx bxs-chevron-down arrow'></i>
          </div>
          <ul class="sub-menu">
            <li><a class="link_name" href="#">Category</a></li>
            <li><a href="#">HTML & CSS</a></li>
            <li><a href="#">JavaScript</a></li>
            <li><a href="#">PHP & MySQL</a></li>
          </ul>
        </li>
        <li>
          <div class="profile-details">
            <div class="profile-content">
              
            </div>
            <div class="name-job">
              <div class="profile_name">{{ request.user.username }}</div>
              <div class="job">Traffic Officer</div>
            </div>
            <i class='bx bx-log-out' onclick="window.location.href='{% url "App_Login:logout" %}'"></i>
          </div>
        </li>
      </ul>
    </div>
    <section class="home-section">
      <div class="home-content">
        <i class='bx bx-menu'></i>
        <span class="text"> Digital Traffic Case Handling Protal </span> <br />
    </div>
    <div>
        {% block main %}
        {% endblock %}
    </div>

    </section>
  </div>

  <script>
    let arrow = document.querySelectorAll(".arrow");
    for (var i = 0; i < arrow.length; i++) {
      arrow[i].addEventListener("click", (e) => {
        let arrowParent = e.target.parentElement.parentElement;//selecting main parent of arrow
        arrowParent.classList.toggle("showMenu");
      });
    }
    let sidebar = document.querySelector(".sidebar");
    let sidebarBtn = document.querySelector(".bx-menu");
    console.log(sidebarBtn);
    /* sidebarBtn.addEventListener("click", () => {
      sidebar.classList.toggle("close");
    }); */
    $(function () {
      /* console.log("width: "+ document.body.clientWidth); */
      
      resizeScreen();
      $(window).resize(function(){
        resizeScreen();
      });
      $('.bx-menu').click(function(){

        if(document.body.clientWidth > 400){
          $('.sidebar').toggleClass('close');
        }else{
          $('.sidebar').toggleClass('small-screen');
        }
      });
      
      function resizeScreen() {
        if(document.body.clientWidth < 400){
          $('.sidebar').addClass('close');
        }else{
          $('.sidebar').removeClass('close');
        }
      }
    });
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" 
  integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>

</html>

templates/App_main/case_register.html
{% extends 'baseElement.html' %}
{% load static %}
{% block title %}
    Case Register
{% endblock %}
{% block main %}
    <style>
        label {
            font-weight: 600;
        }

        #id-driver-table tbody tr {
            padding: 10px;
            cursor: pointer;
        }

        #id-driver-table tbody tr:hover {
            background: #4B49AC;
            color: #ffffff;
        }
    </style>
    <div class="container">
        <div class="col-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title text-center mb-1">Register Case</h4>
                    <p class="card-description text-center">
                        Only Accessible for the traffic control
                    </p>
                    <form class="forms-sample" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                        <div class="form-group">
                            <label for="exampleInputName1">Accused</label>
                            <input class="form-control" name="accused" id="id_accused" type="hidden" value=""
                                   placeholder="Selected Location">
                            <input class="form-control" name='accused_search' id='id-accused-search' type='text'
                                   onkeyup="FilterKeyWord();"
                                   placeholder="Search the driving license">
                            <table id="id-driver-table" style="display: none;">
                                <tbody>
                                {% for driver in all_driver %}
                                    <tr>
                                        <td data-label="Location" onclick="selectedLocation(`{{ driver.id }}`,`{{ driver }}`)">
                                            {{ driver }}
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail3">Vehicle Number</label>
                            {{ form.vehicle_number }}
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword4">Offence</label>
                            {{ form.offence }}
                        </div>
                        <div class="form-group">
                            <label for="exampleSelectGender">Offence Place</label>
                            {{ form.offence_happens_in_place }}
                        </div>
                        <div class="form-group">
                            <label for="exampleTextarea1">Offence Time</label>
                            {{ form.occurrence_happened_time }}
                        </div>
                        <div class="form-group">
                            <label for="exampleInputCity1">Case Type</label>
                            {{ form.caseType }}
                        </div>
                        <div class="form-group">
                            <label for="exampleInputCity1">Cost of Penalty</label>
                            {{ form.cost_of_penalty }}
                        </div>
                        <button type="submit" class="btn btn-primary mr-2">Submit</button>
                        <button class="btn btn-light">Cancel</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script>
        let inputs = document.getElementsByTagName('input');
        let select = document.getElementsByTagName('select');
        for (const input of inputs) {
            input.classList.add('form-control');
        }

        for (const selectElement of select) {
            selectElement.classList.add('form-control');
        }

    </script>

    <script id="table-script" type="text/javascript">
        // Specific column search script
        function FilterKeyWord() {
            // Declare variables
            var input, filter, table, tr, td, i;
            input = document.getElementById("id-accused-search");
            filter = input.value.toLowerCase();
            table = document.getElementById("id-driver-table");
            tr = table.getElementsByTagName("tr");
            table.style.display = 'block';

            // Loop through all table rows, and hide those who don't match the search query
            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[0];
                // change index to change your column search

                if (td) {
                    if (td.innerHTML.toLowerCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
            if (input.value === '') {
                table.style.display = 'none';
            }
        }

        function selectedLocation(accused_id, accused) {
            var theLocation = document.getElementById("id_accused");
            theLocation.setAttribute('value', accused_id);
            document.getElementById("id-accused-search").value = accused;
            document.getElementById("id-driver-table").style.display = 'none';
        }
    </script>
{% endblock %}

{% block script %}
dashboard.classList.remove('active');
caseRegister.classList.add('active');
licenseCheck.classList.remove('active');
signBook.classList.remove('active');
trafficRules.classList.remove('active');
{% endblock %}

templates/App_main/checkDrivingLicense.html
{% extends 'baseElement.html' %}
{% block title %}
    License Check
{% endblock %}
{% block main %}
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <style>
        table {
            border: 1px solid #ccc;
            border-collapse: collapse;
            margin: 0;
            padding: 0;
            width: 100%;
            table-layout: fixed;
        }

        h3.caption {
            text-align: center;
            font-weight: 700;
        }

        table tr {
            background-color: #ffffff;
            border: 1px solid #ddd;
            padding: .35em;
        }

        table th,
        table td {
            padding: .625em;
            text-align: center;
        }

        table th {
            font-size: .85em;
            letter-spacing: .1em;
            text-transform: uppercase;
        }

        @media screen and (max-width: 600px) {
            table {
                border: 0;
            }

            table caption {
                font-size: 1.3em;
            }

            table thead {
                border: none;
                clip: rect(0 0 0 0);
                height: 1px;
                margin: -1px;
                overflow: hidden;
                padding: 0;
                position: absolute;
                width: 1px;
            }

            table tr {
                border-bottom: 3px solid #ddd;
                display: block;
                margin-bottom: .625em;
            }

            table td {
                border-bottom: 1px solid #ddd;
                display: block;
                font-size: .8em;
                text-align: right;
            }

            table td::before {
                /*
                * aria-label has no advantage, it won't be read inside a table
                content: attr(aria-label);
                */
                content: attr(data-label);
                float: left;
                font-weight: bold;
                text-transform: uppercase;
            }

            table td:last-child {
                border-bottom: 0;
            }
        }


        /* general styling */
        body {
            font-family: 'Marcellus', serif !important;
            line-height: 1.25;
        }
    </style>
    <div class="container">
        <h3 class="caption">Driving License List</h3>
        <div class="row mt-4 mb-4 justify-content-center">
            <input type="text" class="form-control w-50" id="id-license-search">
            <button class="btn btn-inverse-warning text-dark" onclick="FilterKeyWord()">search</button>
        </div>
        <table>
            <thead>
            <tr>
                <th scope="col">License Name</th>
                <th scope="col">License Number</th>
                <th scope="col">Mobile Number</th>
                <th scope="col">Address</th>
            </tr>
            </thead>
            <tbody id="id-driver-table">
            {% for driver in all_driver %}
                <tr>
                    <td data-label="License Name">{{ driver.user.first_name }} {{ driver.user.last_name }}</td>
                    <td data-label="License Number">{{ driver.driving_license }}</td>
                    <td data-label="Mobile Number">{{ driver.mobile_number }}</td>
                    <td data-label="Address">{{ driver.house }}, {{ driver.city }}-{{ driver.zipcode }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <script>
        var input, filter, table, tr, td, i;
        input = document.getElementById("id-license-search");
        table = document.getElementById("id-driver-table");

        function FilterKeyWord() {
            // Declare variables
            filter = input.value.toLowerCase();
            tr = table.getElementsByTagName("tr");

            // Loop through all table rows, and hide those who don't match the search query
            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[1];
                // change index to change your column search

                if (td) {
                    if (td.innerHTML.toLowerCase().indexOf(filter) > -1) {
                        Swal.fire(
                            'Great!',
                            'License Found!',
                            'success'
                        )
                    } else {
                        Swal.fire({
                            icon: 'error',
                            title: 'Oops...',
                            text: 'Not Found!',
                            footer: '<a href="{% url 'App_main:case-register' %}">কেস করতে চান?</a>'
                        })
                    }
                }
            }
        }
    </script>
{% endblock %}

{% block script %}
dashboard.classList.remove('active');
caseRegister.classList.remove('active');
licenseCheck.classList.add('active');
signBook.classList.remove('active');
trafficRules.classList.remove('active');
{% endblock %}

templates/App_main/rule_book.html
{% extends 'baseElement.html' %}
{% load static %}
{% block title %}
    Rules
{% endblock %}
{% block main %}
    <style>
        iframe {
            width: 100%;
            height: 100%;
        }
    </style>
    <iframe id="iframeId" src="{% static 'pdf/Road_Sign_Manual.pdf' %}" frameborder="0"></iframe>
{% endblock %}

{% block script %}
dashboard.classList.remove('active');
caseRegister.classList.remove('active');
licenseCheck.classList.remove('active');
signBook.classList.add('active');
trafficRules.classList.remove('active');
{% endblock %}

templates/App_main/traffic_rule.html
{% extends 'baseElement.html' %}
{% block title %}
    Rules
{% endblock %}
{% block main %}
    <style>
        table {
            border: 1px solid #ccc;
            border-collapse: collapse;
            margin: 0;
            padding: 0;
            width: 100%;
            table-layout: fixed;
        }

        h3.caption {
            text-align: center;
            font-weight: 700;
        }

        table tr {
            background-color: #ffffff;
            border: 1px solid #ddd;
            padding: .35em;
        }

        table tr:hover {
            background: #4B49AC;
            color: #ffffff;
        }

        table th,
        table td {
            padding: .625em;
            text-align: center;
        }

        table th {
            font-size: .85em;
            letter-spacing: .1em;
            text-transform: uppercase;
        }

        @media screen and (max-width: 600px) {
            table {
                border: 0;
            }

            table caption {
                font-size: 1.3em;
            }

            table thead {
                border: none;
                clip: rect(0 0 0 0);
                height: 1px;
                margin: -1px;
                overflow: hidden;
                padding: 0;
                position: absolute;
                width: 1px;
            }

            table tr {
                border-bottom: 3px solid #ddd;
                display: block;
                margin-bottom: .625em;
            }

            table td {
                border-bottom: 1px solid #ddd;
                display: block;
                font-size: .8em;
                text-align: right;
            }

            table td::before {
                /*
                * aria-label has no advantage, it won't be read inside a table
                content: attr(aria-label);
                */
                content: attr(data-label);
                float: left;
                font-weight: bold;
                text-transform: uppercase;
            }

            table td:last-child {
                border-bottom: 0;
            }
        }


        /* general styling */
        body {
            font-family: 'Marcellus', serif !important;
            line-height: 1.25;
        }
    </style>
    <div class="container">
        <table>
            <thead>
            <tr>
                <th scope="col">Section Number</th>
                <th scope="col">Description</th>
                <th scope="col">Penalty Imposed In 1st Time</th>
                <th scope="col">Penalty Imposed After 1st Time</th>
            </tr>
            </thead>
            <tbody id="id-driver-table">
            {% for offence in all_offences %}
                <tr>
                    <td data-label="Section Number">{{ offence.in_section }}</td>
                    <td data-label="Description">{{ offence.description }}</td>
                    <td data-label="Penalty Imposed In 1st Time">
                        {{ offence.penalty_imposed_on_1st_time }}
                    </td>
                    {% if offence.penalty_imposed_on_2nd_time %}
                        <td data-label="Penalty Imposed In 2nd Time">
                            {{ offence.penalty_imposed_on_2nd_time }}
                        </td>
                    {% else %}
                        <td data-label="Address">Not Mentioned</td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}
{% block script %}
dashboard.classList.remove('active');
caseRegister.classList.remove('active');
licenseCheck.classList.remove('active');
signBook.classList.remove('active');
trafficRules.classList.add('active');
{% endblock %}